// <auto-generated />
using System;
using IntegracjaSystemow.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IntegracjaSystemow.Database.Migrations
{
    [DbContext(typeof(LaptopContext))]
    partial class LaptopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IntegracjaSystemow.Database.Entities.Laptop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClockSpeed")
                        .HasColumnType("integer");

                    b.Property<string>("DiskCapacity")
                        .HasColumnType("text");

                    b.Property<string>("DiskType")
                        .HasColumnType("text");

                    b.Property<string>("GraphicCard")
                        .HasColumnType("text");

                    b.Property<string>("GraphicCardMemory")
                        .HasColumnType("text");

                    b.Property<string>("IsTouchScreen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MemorySize")
                        .HasColumnType("text");

                    b.Property<string>("OperatingSystem")
                        .HasColumnType("text");

                    b.Property<int?>("PhysicalCores")
                        .HasColumnType("integer");

                    b.Property<string>("PhysicalDriveType")
                        .HasColumnType("text");

                    b.Property<string>("Processor")
                        .HasColumnType("text");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScreenDiagonal")
                        .HasColumnType("text");

                    b.Property<string>("ScreenResolution")
                        .HasColumnType("text");

                    b.Property<string>("ScreenSurface")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Laptops");
                });
#pragma warning restore 612, 618
        }
    }
}
